### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by 37integer** [yukara-ikemiya/wavefit-pytorch#1]
hi, i want to ask a question about inference. 
when doing inference, is the model can use mel-spectrogram as input?

**Comment by yukara-ikemiya** [comment]
For now, my `inference` scirpt doesn't support mel-spectrogram input, but you can easily modify the script to accept mel-spectrogarm input as you like.

In `inference.py`, you can find the input audio signal is converted to mel-spectrogram here.
https://github.com/yukara-ikemiya/wavefit-pytorch/blob/3d9d35a6c21c28040b3ae2297a9aebc795ca7c8f/src/inference.py#L126
https://github.com/yukara-ikemiya/wavefit-pytorch/blob/3d9d35a6c21c28040b3ae2297a9aebc795ca7c8f/src/utils/audio_utils.py#L156

All you have to do is to skip the `self.compute_mel` part and input your mel-spectrogram tensor directly.

**Comment by 37integer** [comment]
thank you for your reply, i will try.
